// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-J8fkkH0M-TyMMTMtyMkjYvO7XlCrOfQ',
    appId: '1:1051806151913:web:506f6e0443b8596dc0ec78',
    messagingSenderId: '1051806151913',
    projectId: 'fir-2024-14046',
    authDomain: 'fir-2024-14046.firebaseapp.com',
    databaseURL: 'https://fir-2024-14046-default-rtdb.firebaseio.com',
    storageBucket: 'fir-2024-14046.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK8r00u0vKztNo1SGEFY60D3vEf191iKM',
    appId: '1:1051806151913:android:5aa86dfdff6eee6bc0ec78',
    messagingSenderId: '1051806151913',
    projectId: 'fir-2024-14046',
    databaseURL: 'https://fir-2024-14046-default-rtdb.firebaseio.com',
    storageBucket: 'fir-2024-14046.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfFmW6YK1CGVHSzH_yO5ghHMs0PdbzjV0',
    appId: '1:1051806151913:ios:b822c888b32c88e2c0ec78',
    messagingSenderId: '1051806151913',
    projectId: 'fir-2024-14046',
    databaseURL: 'https://fir-2024-14046-default-rtdb.firebaseio.com',
    storageBucket: 'fir-2024-14046.firebasestorage.app',
    iosBundleId: 'com.example.fPushNotification',
  );
}
